# Generated by Django 4.1.7 on 2023-03-14 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('Emailid', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=40)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('plan', models.CharField(max_length=50)),
                ('Joindate', models.DateField(max_length=40)),
                ('Expiredate', models.DateField(max_length=40)),
                ('Initialamount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('amount', models.CharField(max_length=15, null=True)),
                ('duration', models.CharField(max_length=15, null=True)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('Plans', models.ManyToManyField(to='app1.plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
